src/Application/PreferencesManager/PreferencesManager.cc
src/Application/PreferencesManager/PreferencesManager.h

Unused function didn't have a return type. VS2013 did not like.

Windows build fix

---

src/Application/Filters/Actions/ActionWatershedFilter.cc
src/Application/Filters/Actions/ActionWatershedFilter.h
src/Application/Filters/CMakeLists.txt
src/Application/Tools/CMakeLists.txt
src/Application/Tools/WatershedFilter.cc
src/Application/Tools/WatershedFilter.h
src/Interface/ToolInterface/CMakeLists.txt
src/Interface/ToolInterface/WatershedFilterInterface.cc
src/Interface/ToolInterface/WatershedFilterInterface.h
src/Interface/ToolInterface/WatershedFilterInterface.ui

An initial implementation of the ITK Watershed filter.  There is much that can be improved.  See notes in src/Application/Filters/Actions/ActionWatershedFilter.cc

Added watershed filter

---

src/Application/Layer/LayerActionParameter.cc
src/Core/Action/Action.cc
src/Core/Action/Action.h
src/Core/Action/Tests/ActionTests.cc
src/Interface/Application/ControllerActionHistory.cc
src/Interface/Application/ControllerInterface.cc
src/Interface/Application/ControllerInterface.h
src/Interface/Application/ControllerInterface.ui
src/Interface/Application/PythonConsoleWidget.cc

Tested on OS X and Windows so far.

Controller action improvements

---

src/Application/Filters/Actions/ActionCurvatureAnisotropicDiffusionFilter.cc
src/Application/Tools/CurvatureAnisotropicDiffusionFilter.cc

Curvature ani diff fix

---

Superbuild/TetgenExternal.cmake

Try updating tetgen

---

src/CMake/Scripts/repair_package.sh.in
src/Core/TextRenderer/TextRenderer.cc

Can view slice numbers on OS X 10.13

SliceNumbers

---

src/Interface/Application/ApplicationInterface.cc

Should open any file that Seg3D supports with a double click.

DicomDoubleClick

---

src/Application/Layer/DataLayer.cc
src/Application/Layer/DataLayer.h
src/Application/Layer/LargeVolumeLayer.h
src/Application/Layer/LayerManager.cc
src/Application/Layer/LayerScene.h
src/Application/PreferencesManager/PreferencesManager.cc
src/Application/Renderer/Renderer.cc
src/Application/Renderer/SliceShader.cc
src/Application/Renderer/SliceShader.frag
src/Application/Renderer/SliceShader.h
src/Application/Viewer/Viewer.cc
src/Interface/Application/LayerWidget.cc

First version of data layer colors.

DataLayerColormap

---

src/Interface/Application/ProjectWizard.cc
src/Interface/Application/ProjectWizard.h

Create new folder from Splashscreen doesn’t go behind anymore.

Bringtofront

---

src/Interface/ToolInterface/ThresholdToolInterface.cc
src/QtUtils/Widgets/QtHistogramWidget.ui

Only sets histogram tooltip where it’s needed.

HistToolTip

---

src/Application/LayerIO/Actions/ActionExportIsosurface.cc
src/Core/Isosurface/Isosurface.cc
src/Core/Isosurface/Isosurface.h
src/Core/Isosurface/IsosurfaceExporter.cc
src/Core/Isosurface/IsosurfaceExporter.h

Isosurface exporter now includes .obj filetypes

ExportIsoObj

---

src/Interface/ToolInterface/MeasurementToolInterface.ui

Made wider so you can see the entire point.

Measurement UI adjustment

---

src/Core/RenderResources/RenderResources.cc
src/Interface/Application/ViewerInterface.cc

Viewer race condition fixed! Works on Windows, OSX, and Linux.

Viewer race condition

---

src/Application/Tools/ThresholdTool.cc

changed max threshold value to default to  machine min

---

src/CMakeLists.txt

version update

---

src/Core/Isosurface/IsosurfaceExporter.cc

STL Writer for Windows

---

src/Interface/Application/Menu.cc
src/Interface/Application/Menu.h

Added a report issue item to Seg3D's help menu

Report issue menu item

---

Superbuild/ImplicitFunctionExternal.cmake
src/Application/Filters/Actions/ActionImplicitModel.cc
src/Application/Filters/Actions/ActionImplicitModel.h

Profile implicit modeling

---

src/Application/Tools/ThresholdTool.cc
src/Application/Tools/ThresholdTool.h
src/Interface/ToolInterface/ThresholdToolInterface.cc
src/Interface/ToolInterface/ThresholdToolInterface.h
src/Interface/ToolInterface/ThresholdToolInterface.ui

Ability to change threshold color.

Threshold color

---

Superbuild/ImplicitFunctionExternal.cmake
src/Application/Filters/Actions/ActionImplicitModel.cc

Fixes Seg3D build and includes parallel implicit model tool.

Parallel implicit model

---

src/Application/Filters/Actions/ActionImplicitModel.cc
src/Application/Renderer/OrientationArrows.cc
src/Core/RenderResources/RenderResources.cc
src/QtUtils/Utils/QtRenderWidget.cc
src/QtUtils/Utils/QtTransferFunctionWidget.cc

Silence GL deprecation messages on OSX

---

.github/workflows/mac.yml
.github/workflows/windows.yml
src/CMakeLists.txt

Update minor and patch version

---

.github/workflows/mac.yml
.github/workflows/windows.yml

Use wildcard for uploading

---

.github/workflows/linux.yml
.travis.yml
Superbuild/Superbuild.cmake

Fixes Seg3D's Travis test build for linux.

Travis linux fix

---

Superbuild/ITKExternal.cmake
src/Application/Tools/GrowCutTool.h

Stable version 5.2 has been tagged earlier this month.

Update ITK to 5.2.0

---

src/CMakeLists.txt

Update patch version
